// Initial career master, transcribed from resume.html.
//
// Each entry carries two keyword lists used for matching against postings:
//   titles — the job titles this entry is evidence for
//   skills — the capabilities it demonstrates
// An agent can fill these in; they are what future matching runs on. This is only used the
// very first time the app runs — after that the saved copy in Blob storage wins,
// so editing this file will NOT change data you have already saved.

const id = (s) => s; // stable, human-readable ids so templates keep pointing at the right item

function seed() {
  return {
    schema: 1,
    version: 1,
    updatedAt: null,
    profile: {
      name: 'Jessica Dougherty',
      headline: 'Controller · SEC/SOX & Technical Accounting · Consolidations · Audit & Tax',
      location: 'San Francisco Bay Area, CA',
      email: 'jessicadougherty4321@gmail.com',
      linkedin: 'linkedin.com/in/jessicaddougherty',
      website: 'jessicadougherty.com',
      summary:
        'CPA-track accounting and finance leader with 15+ years spanning corporate controllership, SEC reporting, SOX compliance, global AR and revenue ($750M+), multi-entity consolidations, and external audit for high-growth public companies including Guardant Health and 10x Genomics. Deep US GAAP technical accounting, month/quarter/year-end close, treasury and cash forecasting, and financial-systems implementation, paired with SOX advisory experience at a national accounting firm. Currently founder and CFO of a fractional finance practice delivering controllership, tax planning, and AI-enabled accounting operations. Seeking a Controller role with a public company, audit or tax firm.',
    },
    sections: [
      {
        key: 'experience',
        title: 'Professional Experience',
        icon: 'briefcase',
        itemNoun: 'role',
        fields: ['org', 'role', 'location', 'dates'],
        items: [
          {
            id: id('exp-fast-insights'),
            status: 'in_progress',
            org: 'Fast Insights IO',
            role: 'Founder & CFO / Fractional Controller',
            location: 'Los Gatos, CA',
            dates: 'Apr 2024 – Present',
            bullets: [
              { id: 'b1', text: 'Provide fractional CFO and controllership services to small and mid-sized businesses — owning the monthly close, bookkeeping, cash and tax planning, financial reporting, and finance-systems setup.' },
              { id: 'b2', text: 'Advise high-net-worth clients on estate, cash, and tax planning; prepare and review filings and support compliance and audit readiness.' },
              { id: 'b3', text: 'Design AI-enabled accounting operations that automate reconciliations, close tasks, and reporting workflows, improving accuracy and turnaround time while maintaining secure data.' },
            ],
            tags: ['controllership', 'tax', 'fractional cfo', 'automation'],
          },
          {
            id: id('exp-scout-quest'),
            status: 'in_progress',
            org: 'Scout Quest Education',
            role: 'Cofounder & CEO',
            location: 'Remote — United States',
            dates: 'Apr 2026 – Present',
            bullets: [
              { id: 'b1', text: 'Founded and lead an education-technology startup; own company finance, budgeting, compliance and data-privacy planning, and operational infrastructure alongside product and strategy.' },
            ],
            tags: ['founder', 'edtech', 'strategy'],
          },
          {
            id: id('exp-guardant'),
            status: 'completed',
            org: 'Guardant Health',
            role: 'Senior Manager — Global AR & Cash | SEC/SOX Lead | Consolidations | Audit | Systems',
            location: 'Palo Alto, CA',
            dates: '2022 – 2024',
            bullets: [
              { id: 'b1', text: 'Led global accounts receivable, cash, and collections for a publicly traded precision-oncology company, owning the related close, reconciliations, and reporting.' },
              { id: 'b2', text: 'Served as SEC/SOX lead for AR and cash cycles — designed, documented, and maintained internal controls and coordinated directly with external and internal auditors on walkthroughs and testing.' },
              { id: 'b3', text: 'Managed multi-entity consolidations and supported technical accounting and financial-systems initiatives across the close.' },
            ],
            tags: ['public company', 'sec', 'sox', 'ar', 'consolidations', 'biotech'],
          },
          {
            id: id('exp-10x'),
            status: 'completed',
            org: '10x Genomics',
            role: 'Senior Manager → Manager → Supervisor, Global AR / Revenue | SEC/SOX Lead | Consolidations | Cash Planning | Systems',
            location: 'Pleasanton, CA',
            dates: '2018 – 2022',
            bullets: [
              { id: 'b1', text: 'Progressed through three roles of increasing scope, leading global AR and revenue operations, SEC/SOX compliance, consolidations, and cash planning for a high-growth public company.' },
              { id: 'b2', text: 'Owned revenue and AR close, account reconciliations, and audit support; partnered with external auditors on quarterly reviews and annual audits.' },
              { id: 'b3', text: 'Served as designated systems leader for accounting initiatives, streamlining the close and strengthening the control environment.' },
            ],
            tags: ['public company', 'sec', 'sox', 'revenue', 'promotion', 'biotech'],
          },
          {
            id: id('exp-connor'),
            status: 'completed',
            org: 'Connor Group',
            role: 'Senior Manager — SOX Implementation Lead',
            location: 'San Jose, CA',
            dates: '2018 – 2019',
            bullets: [
              { id: 'b1', text: 'Advised clients on SOX program design and implementation at a leading technical accounting and advisory firm — scoping controls, leading risk assessments, and preparing audit-ready documentation.' },
            ],
            tags: ['advisory', 'sox', 'consulting', 'technical accounting'],
          },
          {
            id: id('exp-myers-briggs'),
            status: 'completed',
            org: 'The Myers-Briggs Company',
            role: 'Assistant Controller / Director — Accounting | FP&A | Consolidations | Derivatives | ESPP | Royalties',
            location: 'Sunnyvale, CA',
            dates: '2015 – 2018',
            bullets: [
              { id: 'b1', text: 'Directed accounting, FP&A, and multi-entity consolidations across multinational business, including derivatives, ESPP, and royalty accounting.' },
              { id: 'b2', text: 'Owned monthly, quarterly, and annual close, financial reporting, and external audit coordination.' },
            ],
            tags: ['fp&a', 'consolidations', 'derivatives', 'multinational'],
          },
          {
            id: id('exp-ibi'),
            status: 'completed',
            org: 'IBI Group',
            role: 'Controller / Business Manager',
            location: 'San Jose, CA',
            dates: '2013 – 2015',
            bullets: [
              { id: 'b1', text: 'Held full controllership for a regional office; led a strategic reorganization, downsized office locations, and improved reporting, budgeting, and day-to-day financial operations.' },
            ],
            tags: ['controller', 'reorganization', 'budgeting'],
          },
          {
            id: id('exp-allana'),
            status: 'completed',
            org: 'Allana Buick & Bers, Inc.',
            role: 'Assistant CFO & Supervising Project Accountant',
            location: 'Palo Alto, CA',
            dates: '2008 – 2013',
            bullets: [
              { id: 'b1', text: 'Supported the CFO across financial planning, project accounting, estate management, and bank-covenant compliance for a professional-services firm.' },
              { id: 'b2', text: 'Led project planning and job-cost accounting and administered Deltek (project ERP); recognized as an industry subject-matter expert through published PSMJ articles on job-cost accounting.' },
            ],
            tags: ['project accounting', 'deltek', 'erp', 'job cost'],
          },
        ],
      },
      {
        key: 'education',
        title: 'Education',
        icon: 'cap',
        itemNoun: 'degree',
        fields: ['org', 'role', 'dates'],
        items: [
          {
            id: id('edu-uop'),
            status: 'completed',
            org: 'University of Phoenix',
            role: 'B.S., Business Administration — Accounting',
            location: '',
            dates: '',
            bullets: [],
            tags: ['degree'],
          },
          {
            id: id('edu-deanza'),
            status: 'completed',
            org: 'De Anza College',
            role: 'A.A., Business / CIS — Accounting',
            location: '',
            dates: '',
            bullets: [],
            tags: ['degree'],
          },
        ],
      },
      {
        key: 'certifications',
        title: 'Certifications & Affiliations',
        icon: 'badge',
        itemNoun: 'certification',
        fields: ['org', 'role', 'dates'],
        items: [
          {
            id: id('cert-aicpa'),
            status: 'completed',
            org: 'American Institute of Certified Public Accountants (AICPA)',
            role: 'Member',
            location: '',
            dates: '2026 – Present',
            bullets: [],
            tags: ['membership'],
          },
          {
            id: id('cert-cpa'),
            status: 'in_progress',
            org: 'California Board of Accountancy',
            role: 'Certified Public Accountant (CPA)',
            location: '',
            dates: '2026',
            bullets: [
              { id: 'b1', text: 'Final exam completed; results pending.' },
            ],
            tags: ['license', 'cpa'],
          },
          {
            id: id('cert-ctec'),
            status: 'in_progress',
            org: 'CTEC',
            role: 'Registered Tax Preparer',
            location: '',
            dates: '',
            bullets: [
              { id: 'b1', text: 'Exam passed; application pending.' },
            ],
            tags: ['license', 'tax'],
          },
        ],
      },
      {
        key: 'skills',
        title: 'Core Competencies & Systems',
        icon: 'spark',
        itemNoun: 'skill group',
        fields: ['role'],
        items: [
          {
            id: id('skill-technical'),
            status: 'completed',
            org: '',
            role: 'Technical Accounting & Reporting',
            location: '',
            dates: '',
            bullets: [
              { id: 'b1', text: 'SEC Reporting & SOX Compliance' },
              { id: 'b2', text: 'US GAAP Technical Accounting' },
              { id: 'b3', text: 'Multi-Entity & Multi-Currency Consolidations' },
              { id: 'b4', text: 'Revenue Recognition' },
              { id: 'b5', text: 'Derivatives, ESPP & Royalty Accounting' },
            ],
            tags: [],
          },
          {
            id: id('skill-operations'),
            status: 'completed',
            org: '',
            role: 'Finance Operations',
            location: '',
            dates: '',
            bullets: [
              { id: 'b1', text: 'Global AR, Revenue & Cash Management' },
              { id: 'b2', text: 'Month / Quarter / Year-End Close' },
              { id: 'b3', text: 'FP&A & Cash Forecasting' },
              { id: 'b4', text: 'Treasury & Cash Forecasting' },
              { id: 'b5', text: 'External & Internal Audit Management' },
              { id: 'b6', text: 'Tax Planning & Compliance' },
            ],
            tags: [],
          },
          {
            id: id('skill-systems'),
            status: 'completed',
            org: '',
            role: 'Systems & Automation',
            location: '',
            dates: '',
            bullets: [
              { id: 'b1', text: 'ERP & Financial-Systems Implementation (Deltek)' },
              { id: 'b2', text: 'Process Reengineering & Automation' },
              { id: 'b3', text: 'Advanced Microsoft Excel' },
              { id: 'b4', text: 'AI-enabled finance automation' },
            ],
            tags: [],
          },
          {
            id: id('skill-leadership'),
            status: 'completed',
            org: '',
            role: 'Leadership',
            location: '',
            dates: '',
            bullets: [
              { id: 'b1', text: 'Team Leadership & Cross-Functional Partnership' },
            ],
            tags: [],
          },
        ],
      },
      {
        key: 'leadership',
        title: 'Leadership & Recognition',
        icon: 'star',
        itemNoun: 'entry',
        fields: ['org', 'role', 'dates'],
        items: [
          {
            id: id('lead-deltek'),
            status: 'completed',
            org: 'Bay Area Deltek User Group',
            role: 'Leader',
            location: '',
            dates: '',
            bullets: [],
            tags: [],
          },
          {
            id: id('lead-napw'),
            status: 'completed',
            org: 'NAPW – San Jose',
            role: 'Chapter Treasurer',
            location: '',
            dates: '',
            bullets: [],
            tags: [],
          },
          {
            id: id('lead-toastmasters'),
            status: 'completed',
            org: 'Toastmasters International',
            role: 'Member',
            location: '',
            dates: '',
            bullets: [],
            tags: [],
          },
        ],
      },
      {
        key: 'publications',
        title: 'Publications',
        icon: 'doc',
        itemNoun: 'publication',
        fields: ['org', 'role', 'dates'],
        items: [
          {
            id: id('pub-job-cost'),
            status: 'completed',
            org: 'PSMJ',
            role: '“Job Cost Accounting Secrets”',
            location: '',
            dates: '',
            bullets: [],
            tags: ['article'],
          },
          {
            id: id('pub-team-training'),
            status: 'completed',
            org: 'PSMJ',
            role: '“Team in Training”',
            location: '',
            dates: '',
            bullets: [],
            tags: ['article'],
          },
        ],
      },
      {
        key: 'events',
        title: 'Events & Speaking',
        icon: 'calendar',
        itemNoun: 'event',
        fields: ['org', 'role', 'location', 'dates'],
        items: [],
      },
      {
        key: 'hackathons',
        title: 'Hackathons',
        icon: 'bolt',
        itemNoun: 'hackathon',
        fields: ['org', 'role', 'location', 'dates'],
        items: [],
      },
      {
        key: 'languages',
        title: 'Languages',
        icon: 'globe',
        itemNoun: 'language',
        fields: ['role'],
        items: [
          {
            id: id('lang-basics'),
            status: 'in_progress',
            org: '',
            role: 'Conversational basics',
            location: '',
            dates: '',
            bullets: [
              { id: 'b1', text: 'Spanish, French, Italian, German' },
            ],
            tags: [],
          },
        ],
      },
    ],
  };
}

module.exports = { seed };
